POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "",
    "password": "du2006"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "lovanbang",
    "email": "lovanbangbox9@gmail.com",
    "password": "bang1234"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTBmZWQzYjg2NzdmNDFjNTkyNGY5MDQiLCJpYXQiOjE2OTU1NDI1ODd9.GCJ4lqlV014n4k4tC3eP1nlbVQsK_G2_XUmV-CcaWpU

{
    "title": "React",
    "description": "React",
    "url": "react.com"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTBmMGI1ZmNlZmM3MzYxYjc1OTBhNGMiLCJpYXQiOjE2OTU1NDg4NzV9.P91UExDf8V4CUKhy8RMQJb_01jB7KizhgeRuDA9LYzA

###
PUT http://localhost:5000/api/posts/650fe4520bd64f728453d86f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTBmMGI1ZmNlZmM3MzYxYjc1OTBhNGMiLCJpYXQiOjE2OTU1NDg4NzV9.P91UExDf8V4CUKhy8RMQJb_01jB7KizhgeRuDA9LYzA

{
    "title": "Vue",
    "description": "Vueeee",
    "url": "https://vue.org"
}

###
DELETE http://localhost:3000/api/posts/650fe4520bd64f728453d86f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTBmMGI1ZmNlZmM3MzYxYjc1OTBhNGMiLCJpYXQiOjE2OTU1NDg4NzV9.P91UExDf8V4CUKhy8RMQJb_01jB7KizhgeRuDA9LYzA